# Generated by Django 3.1.2 on 2022-06-05 23:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='date')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.CharField(max_length=150, primary_key=True, serialize=False, unique=True, verbose_name='product_id')),
                ('name', models.CharField(max_length=150, verbose_name='product_name')),
                ('price', models.FloatField(verbose_name='product_price')),
                ('stock', models.IntegerField(default=0, verbose_name='product_stock')),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuantity', models.IntegerField(default=0, verbose_name='cuantity')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_detail_order', to='products.order')),
                ('product', models.ManyToManyField(related_name='order_product', to='products.Product')),
            ],
        ),
    ]
